---
title: "analysis"
author: "Lucky Mehra"
date: "9/17/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load-packages}
pacman::p_load(tidyverse,
               qdapRegex,
               patchwork)
```

```{r}
sweetpotato <- read_csv(here::here('data/clean-data', 'sweetpotato.csv')) %>% 
  mutate(yield_wf_num_1 = if_else(!is.na(yield_wf_petite_1),
                                 yield_wf_num_1 + yield_wf_petite_1,
                                 yield_wf_num_1),
         
         yield_weedy_num_1 = if_else(!is.na(yield_weedy_petite_1),
                                     yield_weedy_num_1 + yield_weedy_petite_1,
                                     yield_weedy_num_1)) %>% 
  dplyr::select(-yield_wf_petite_1, -yield_weedy_petite_1) %>% 
  mutate(yield_wf_marketable = yield_wf_num_1 + yield_wf_jumbo,
         yield_wf_total = yield_wf_marketable + yield_wf_canner,
         yield_weedy_marketable = yield_weedy_num_1 + yield_weedy_jumbo,
         yield_weedy_total = yield_weedy_marketable + yield_weedy_canner)

# calculate marketable and total yield loss
yieldloss <- sweetpotato %>% 
  mutate(marketable_loss = ((yield_wf_marketable - yield_weedy_marketable)/yield_wf_marketable)*100,
         
         total_loss = ((yield_wf_total - yield_weedy_total)/yield_wf_total)*100)

# clean some variables for consistency
yieldloss <- yieldloss %>% 
  mutate(location_information = if_else(location_information == "Horticultural Crops Research Station",
                                        "Horticultural Crops Research Station, Clinton, NC",
                                        location_information)) %>% 
  mutate(location_information = str_replace_all(location_information, c("-" = ",", "Georgetown" = "Georgetown,")),
         location = ex_city_state(location_information),
         location = str_replace(location, ", ", "_"),
         soil_type = str_replace(soil_type, "loamy sand", "loamy_sand")) %>% 
  relocate(year, location, variety, primary_weed, soil_type,
           irrigation_type, irrigation_type_present, pi, marketable_loss,
           total_loss)
```

```{r}
yieldloss %>% 
  count(pi, ssort = TRUE)

yieldloss %>% 
  count(variety, sort = TRUE)

yieldloss %>% 
  count(soil_type, sort = TRUE)

yieldloss %>% 
  count(primary_weed, sort = TRUE)

yieldloss %>% 
  count(irrigation_type, sort = TRUE)

yieldloss %>% 
  count(location, sort = TRUE)
```

Make figures.

```{r figures}

# histogram  of marketable loss
hist_market <- yieldloss %>% 
  ggplot(mapping = aes(x = marketable_loss)) +
  geom_histogram()
# histogram of total loss
# hist_total <- yieldloss %>% 
#   ggplot(mapping = aes(x = total_loss)) +
#   geom_histogram()
# 
# hist_market / hist_total

# yield loss by location
year_market <- yieldloss %>% 
  dplyr::filter(!is.na(year)) %>% 
  ggplot(mapping = aes(x = as_factor(year), y = marketable_loss)) +
  geom_boxplot()

# year_total <- yieldloss %>% 
#   dplyr::filter(!is.na(year)) %>% 
#   ggplot(mapping = aes(x = as_factor(year), y = total_loss)) +
#   geom_boxplot()

# graphs of marketable yield loss and total yield loss are very similar
# therefore, only goint to plot marketable yield loss

year_market

# create a function to plot by different variables
plot_market_loss_by <- function(var){
  yieldloss %>% 
  dplyr::filter(!is.na({{var}})) %>% 
  ggplot(mapping = aes(x = as_factor({{var}}), y = marketable_loss)) +
  geom_boxplot() +
    coord_flip()
}

# year
plot_market_loss_by(year)

# location
plot_market_loss_by(location)

# variety
plot_market_loss_by(variety)

# primary weed
plot_market_loss_by(primary_weed)

# soil type
plot_market_loss_by(soil_type)

# irrigation type
plot_market_loss_by(irrigation_type)
```



